- name: install nodejs package
  yum:
    name:  '{{ item }}'
    state: present
  with_items:
    - http://ftp.riken.jp/Linux/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - nodejs

# - name: start nodejs service
#   service:
#     name:    nodejs
#     enabled: yes
#     state:   restarted

