#!/bin/sh
### BEGIN INIT INFO
# Provides: eye
# Required-Start: $network $remote_fs $syslog $local_fs
# Required-Stop: $network $remote_fs $syslog $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: control eye
### END INIT INFO

RBENV_PATH=/usr/local/rbenv
PATH="/usr/local/bin:$RBENV_PATH/shims:$PATH"

EYE=eye
CONFIG_FILE=/etc/eye/main.eye
RUNAS=root

execute() {
  CMD="$EYE $1 $2"

  if [ "$USER" = "$RUNAS" ]; then
    $CMD
  else
    su $RUNAS -c "$CMD"
  fi
}

case "$1" in
  start)
    echo -n "Loading eye configuration for $SERVICE_NAME"
    execute load $CONFIG_FILE
    execute start all
    ;;
  stop)
    execute stop all
    ;;
  restart)
    execute restart all
    ;;
  status)
    execute info
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
