- name: set application path
  set_fact:
    app:
      path: '{{ user.path }}/{{ app.name }}'

- name: create application directory
  file:
    path:  '{{ app.path }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    state: directory

- name: create shared directory
  file:
    path:    '{{ app.path }}/shared/{{ item }}'
    state:   directory
    recurse: yes
  with_items:
    - tmp/sockets
    - tmp/pids

- name: change owner of the shared directory
  file:
    path:    '{{ app.path }}/shared'
    recurse: yes
    owner:   '{{ user.name }}'
    group:   '{{ user.name }}'

