- name: install backup gem
  command: bash -lc 'gem install backup --no-ri --no-rdoc'

- name: create directory
  command: mkdir -p /root/Backup/models

- name: copy config.rb
  template:
    src:  config.rb
    dest: /root/Backup/config.rb

- name: copy database_backup.rb
  template:
    src:  database_backup.rb
    dest: /root/Backup/models/database_backup.rb

- name: register cron
  cron:
    name:   'Backup at 4am every day'
    hour:   '4'
    minute: '0'
    job:    '/bin/bash -lc "backup perform -t database_backup"'

