- name: set application path
  set_fact:
    app_path: '{{ user_path }}/{{ app_name }}'

- name: create application directory
  file:
    path:  '{{ app_path }}'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: directory

- name: create shared directory
  file:
    path:    '{{ app_path }}/shared/{{ item }}'
    state:   directory
    recurse: yes
  with_items:
    - tmp/sockets
    - tmp/pids
    - nginx

- name: change owner of the shared directory
  file:
    path:    '{{ app_path }}/shared'
    recurse: yes
    owner:   '{{ user_name }}'
    group:   '{{ user_name }}'

